version: '3.8'
volumes:
  cache:
    driver: local
  db:
    driver: local
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eSYzVUxnUzgkb0RLV28meDE0SlVJeDEqd2FwTCVYM05YQVJE
    volumes: 
      - cache:/data
  postgres:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kaspapool
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./data/pg/:/docker-entrypoint-initdb.d/

