{
 "title": "Pool Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "show_balances", "query": "1,0" },
   { "name": "wallet_filter", "query": { "query": "ks_valid_share_counter" } }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "# Solo mining Pool - WIP\n\nFee:      0%\n\nPool URL: kas-us-east.ghost-pool.io:5555\n\nUse `wallet_filter` above to filter to a specific miner\n\nPlease report any issues to https://github.com/onemorebsmith/kaspa-stratum-bridge/discussions/34"
   }
  },
  {
   "title": "Blocks Mined",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(ks_blocks_mined{wallet=~\"${wallet_filter}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Est. Time to Win",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 / (1 - (1 - ((SUM(rate(ks_valid_share_counter{wallet=~\"${wallet_filter}\"}[10m])) * 17179900) / SUM(ks_estimated_network_hashrate_gauge))) ^ ((SUM(delta(ks_network_block_count[10m])) * 144)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Difficulty (K)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " avg(ks_network_difficulty_gauge) / 1000000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Hashrate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(ks_estimated_network_hashrate_gauge)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM (ks_balance_by_wallet_gauge{wallet=~\"${wallet_filter}\"}) * ${show_balances}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "MAX(ks_network_block_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Hashrates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM   (rate(ks_valid_share_counter{wallet=~\"${wallet_filter}\"}[1m]) * 17179900) ",
     "legendFormat": "1m"
    },
    {
     "expr": "SUM   (rate(ks_valid_share_counter{wallet=~\"${wallet_filter}\"}[1h]) * 17179900)",
     "legendFormat": "1h"
    },
    {
     "expr": "SUM   (rate(ks_valid_share_counter{wallet=~\"${wallet_filter}\"}[1d]) * 17179900)",
     "legendFormat": "1d"
    }
   ]
  },
  {
   "title": "Balance Change [1d]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(delta(ks_balance_by_wallet_gauge{wallet=~\"${wallet_filter}\"}[24h])) *  ${show_balances}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "COUNT(COUNT BY(worker) (ks_valid_share_counter{wallet=~\"${wallet_filter}\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Participation [10m]",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "shares/m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM BY (wallet) (rate(ks_valid_share_counter[10m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hashrate by Worker",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "targets": [
    {
     "expr": "SUM BY(worker)  (rate(ks_valid_share_counter{wallet=~\"${wallet_filter}\"}[10m]) * 17179900) ",
     "legendFormat": "{{worker}}"
    },
    {
     "expr": "SUM (rate(ks_valid_share_counter{wallet=~\"${wallet_filter}\"}[10m]) * 17179900)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Client Error Rates",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "SUM BY(error) (rate(ks_worker_errors[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rejected Shares",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "SUM BY(worker, type) (rate(ks_invalid_share_counter[$__rate_interval]))",
     "legendFormat": "{{worker}}_{{type}}"
    }
   ]
  },
  {
   "title": "Hashrate by Miner",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "SUM BY (miner) (rate(ks_valid_share_counter{wallet=~\"${wallet_filter}\"}[10m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shares per Minute",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "SUM BY (worker) (rate(ks_valid_share_counter{wallet=~\"${wallet_filter}\"}[5m])) * 60",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Blocks Mined",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "SUM (ks_blocks_mined{wallet=~\"${wallet_filter}\"})",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Wallet Balances",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "AVG BY(wallet) (ks_balance_by_wallet_gauge{wallet=~\"${wallet_filter}\"}) *  ${show_balances}",
     "legendFormat": "{{wallet}}"
    }
   ]
  },
  {
   "title": "Network Stats",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "targets": [
    {
     "expr": "MAX(ks_estimated_network_hashrate_gauge)",
     "legendFormat": "hashrate"
    },
    {
     "expr": "MAX(ks_network_difficulty_gauge)",
     "legendFormat": "difficulty"
    }
   ]
  },
  {
   "title": "Estimated Time to Win",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "1 / (1 - (1 - ((SUM(rate(ks_valid_share_counter{wallet=~\"${wallet_filter}\"}[10m])) * 17179900) / SUM(ks_estimated_network_hashrate_gauge))) ^ ((SUM(delta(ks_network_block_count[10m])) * 144)))",
     "legendFormat": "Estimate"
    }
   ]
  },
  {
   "title": "Network Block Rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "blocks/s" } },
   "targets": [
    {
     "expr": "SUM(clamp(delta(ks_network_block_count[1m]), 0, 180)) / 60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}