apiVersion: apps/v1
kind: Deployment
metadata:
  name: pool-worker
  namespace: pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pool-worker
  template:
    metadata:
      labels:
        app: pool-worker
    spec:
      containers:
      - name: pool-worker-sha256-1
        args:
            - -prom=:2112
            - -hcp=:5556
            - -kaspa=kaspad-service.default:16110
            - -pg=postgres://pooladmin:a0R4Jk10MG1qODg5NEFecEMxWGlQdFp1OTFESEJwUWU5cyF1R0k2RA@postgres-service.data:5432/kaspapool
            - -wallet=kaspa:qrstlz0uwkcrsrfswywfzesjek40d2m94mgq23xwwrjhav2qgzc9q4mxhjpau
            - -redis=redis-service.data:6379
        image: us-east1-docker.pkg.dev/praxis-paratext-363002/kaspapool/worker:latest
        imagePullPolicy: Always
        name: bridge-sha256-1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 5556
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 100Mi